# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

- task: Docker@2
  inputs:
    containerRegistry: 'blazercontainerregistry-4841'
    repository: 'new_blazer_test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'